export const theme = {
	colors: {
		colorTitle: "#605454",
	},
    fontSizes: {
		FONT_SIZE_XXXXXS: "9px",
		FONT_SIZE_XXXXS: "10px",
		FONT_SIZE_XXXS: "12px",
		FONT_SIZE_XXS: "13px",
		FONT_SIZE_XS: "14px",
		FONT_SIZE_S: "16px",
		FONT_SIZE_M: "17px",
		FONT_SIZE_XMS: "20px",
		FONT_SIZE_XM: "22px",
		FONT_SIZE_L: "28px",
		FONT_SIZE_ML: "25px",
		FONT_SIZE_XL: "32px",
		FONT_SIZE_XXL: "40px",
    },
    fontWeight: {
		FONT_WEIGHT_LIGHT: "300",
		FONT_WEIGHT_REGULAR: "400",
		FONT_WEIGHT_MEDIUM: "500",
		FONT_WEIGHT_BOLD: "600",
    },
    spacing: {
		SPACING_ZERO: "0rem",
		SPACING_XS: "0.1rem",
		SPACING_S: "0.25rem",
		SPACING_M: "0.5rem",
		SPACING_XMS: "0.75rem",
		SPACING_XML: "1rem",
		SPACING_XM: "1.5rem",
		SPACING_L: "2rem",
		SPACING_XL: "2.5rem",
		SPACING_XXL: "3rem",
	},
};
